### PR TITLE
Feature: high level launch

### PR DESCRIPTION
**Pull request by Olavhaasie**
Partly closes PM-96

## Description
Made some small fixes for the future high level launch file.

## Changes
* Fix the use of private parameters
* Rename topics to global topics by adding `/`
* Change _some_ double quotes to single quotes (turned out to be a lot more actually :man_shrugging: )

### CODE REVIEW

**Comment by Roelemans** [comment]
> Change some single quotes to double quotes

You seem to have changed double quotes to single ones? I would expect to use double quotes in these locations. Can you explain why you use single quotes?

**Comment by Olavhaasie** [comment]
> > Change some single quotes to double quotes
> 
> You seem to have changed double quotes to single ones? I would expect to use double quotes in these locations. Can you explain why you use single quotes?

Single and double quotes are identical in Python. Right now we use them both and I would like to use single quotes everywhere.

**Comment by Roelemans** [comment]
> Change some single quotes to double quotes

This message is the other way around, please fix it. Is it a (future) idea to add a requirement to the linter?

**Review by Roelemans — APPROVED** [review]

**Comment by Olavhaasie** [comment]
> This message is the other way around, please fix it. Is it a (future) idea to add a requirement to the linter?

Ah I see I made a mistake in the PR description

**Pull request merged**
