### PR TITLE
Feature/new images in monitor ipd

### PR DESCRIPTION
**Pull request by gaiavdh**
## Description
 Added new images in the monitor input device. (All credits for designing and making the images go to Julia!) We believe that aside from looking nicer of course, it should also be more clear now which button to select as you have not only text to judge from. Could you please test if it is clear enough which gait button is which gait?

## Changes

* Deleted old, (now) unused images.
* Added new images for the monitor input device and used those as buttons.
* Slightly rearranged the order of a few buttons, to have the rocker switch closer to the waking gait, as I think that makes more sense.

### CODE REVIEW

**Review by RutgerVanBeek — CHANGES_REQUESTED** [review]
First of all this is really nice! (Also thanks to @juliagreeven ). The rocker switch up and down are now to small walk and large walk, but for going from small to medium you would also use the rocker switch up (@JorisWeeda ?), then this picture is a bit confusing. Secondly I remember that the gait side step step small was equal to medium and that we therefore did not use this, is this correct? May be you can remove the button if that is the case.

**Comment by gaiavdh** [comment]
The gait side step small is actually different from the side step normal. We have never used it, but it is an existing gait so I think it is best to leave the buttons in the input device, we might want to use it later. It was the small walk and medium walk that were the same, but as we now have variable step size (and therefore might start using different step sizes more - and also have actual different step sizes, for that matter) I thought it would be nice to leave buttons for small walk and large walk in the input device.
And about the rocker switch: I believe you are correct. Maybe something like 'larger step' and 'smaller step' would be better to have as text on the images? @juliagreeven do you think you can change that in the images?

**Comment by Joris-JW** [comment]
> The gait side step small is actually different from the side step normal. We have never used it, but it is an existing gait so I think it is best to leave the buttons in the input device, we might want to use it later. It was the small walk and medium walk that were the same, but as we now have variable step size (and therefore might start using different step sizes more - and also have actual different step sizes, for that matter) I thought it would be nice to leave buttons for small walk and large walk in the input device.
> And about the rocker switch: I believe you are correct. Maybe something like 'larger step' and 'smaller step' would be better to have as text on the images? @juliagreeven do you think you can change that in the images?

I agree with Gaia to have a 'larger step' and 'smaller step'. This way the buttons can be used for different gaits and more step sizes can be added! The rest looks nice!!

**Comment by gaiavdh** [comment]
The images for the rocker switch are changed. They now read 'Step size up' and 'Step size down'.

**Review by Olavhaasie — APPROVED** [review]

**Review by RutgerVanBeek — APPROVED** [review]

**Review by Roelemans — APPROVED** [review]

**Comment by RutgerVanBeek** [comment]
Wow echt ineens allemaal tegelijk.

**Pull request merged**
